### ISSUE TITLE
always generate a erl_crash.dump file in home directory

### ISSUE THREAD

**Issue by ljhui** [flathub/net.sonic_pi.SonicPi#7]
thanks to author's great work, I'm searching package for fedora 35 and find this. After install it seems work well, I'm newbie to sonic pi, so I haven't test all, but sonic pi will genarate a erl_crash.dump file when it startups, it's really annoying though I doesn't find problems with the app so far.
[erl_crash.dump.txt](https://github.com/flathub/net.sonic_pi.SonicPi/files/7778228/erl_crash.dump.txt)

**Comment by hfiguiere** [comment]
I'm seeing this too. It's actually the current directory (which is the home dir if started from the UI)

**Comment by hfiguiere** [comment]
I can't reproduce anymore with 4.4 (soon to be published)
